e2e-tests - folder structure
digitalservicebund/a2j-rechtsantragstelle pull request #1072
Opened 2024-08-12 12:21 UTC by rbrtrfl

For the new Prozesskostenhilfe form, parts of the e2e-tests are to be moved to a shared folder.

2024-08-12 14:19 UTC, frederike-ramin approved these changes
I love it! The only thing I'd suggest is putting `shared` under `flowPages`:

- flowPages
  - bh
  - pkh
  - shared
- util
- etc

And maybe skip the test in `tests/e2e/flowPages/prozesskostenhilfe/formular/prozesskostenhilfe.formular.spec.ts` instead of commenting it out if it doesn't work yet? (Or don't commit it in the first place :) )

2024-08-13 06:55 UTC, aaschlote commented on tests/e2e/flowPages/beratungshilfe/beratungshilfe.spec.ts
>    await page.goto("/beratungshilfe");
This file shouldn't on the pages folder? Technically is not a flow page, but a normal page, right?

2024-08-13 06:58 UTC, aaschlote commented on tests/e2e/flowPages/beratungshilfe/vorabcheck/csrf.spec.ts
> +import { CookieSettings } from "../../../pom/CookieSettings";
I believe this is not in the correct folder, here it's testing the execution of csrf on the Beratungshilfe Vorabcheck pages, so the tests are checking the csrf and not the Beratungshilfe Vorabcheck. Can we move to a new folder, like common?

2024-08-13 06:58 UTC, aaschlote commented on tests/e2e/flowPages/beratungshilfe/vorabcheck/userfeedback.vorabcheck.spec.ts
> +import { CookieSettings } from "../../../pom/CookieSettings";
Same here

2024-08-13 06:59 UTC, aaschlote commented on tests/e2e/flowPages/beratungshilfe/vorabcheck/hiddenfields.spec.ts
> +import { BeratungshilfeVorabcheck } from "../../../pom/BeratungshilfeVorabcheck";
same here

2024-08-13 07:02 UTC, aaschlote requested changes
Nice changes, two things to check:

1. You have some lint warnings, can you get rid of them?
2. You are using too much ``../.../...`` to import some files, could you use the shortcut ``test/`` or create a new one for the e2e path in the tsconfig?

Nice work 😃

2024-08-13 08:39 UTC, merged