pkh-flow fixes
digitalservicebund/a2j-rechtsantragstelle pull request #1154
Opened 2024-09-03 17:14 UTC by rbrtrfl

in the scope of commit

fix(pkh-flow): fix navigation, guards and doneFunctions around staatliche-leistungen

it is required to change the name of the select variable from `staatlicheLeistungenPKH` to `staatlicheLeistungen` in `/prozesskostenhilfe/formular/finanzielle-angaben/einkuenfte/staatliche-leistungen` in Strapi

2024-09-04 11:06 UTC, Spencer6497 requested changes
The code consolidation/reuse here is sensible, but I'm not sure the doneFunction logic is quite correct (unless I missed something?) Happy to discuss as always :)

2024-09-04 11:06 UTC, Spencer6497 commented on app/flows/prozesskostenhilfeFormular/finanzielleAngaben/doneFunctions.ts
> +    }
nit: i think a ternary would be more appropriate here, given that there are only two cases, z.B.
```
return context.staatlicheLeistungen === 'asylbewerberleistungen' || context.staatlicheLeistungen === 'grundsicherung' ? true : <doneFunctions>
```

2024-09-04 11:06 UTC, Spencer6497 commented on app/flows/prozesskostenhilfeFormular/finanzielleAngaben/doneFunctions.ts
>    ["no", "widowed"].includes(context.partnerschaft ?? "") ||
`hasStaatlicheLeistungen` tests for _any_ staatlicheLeistungen, but I think the only case in which we skip over Partner is Grundsicherung or Asylbewerberleistungen

2024-09-04 11:06 UTC, Spencer6497 commented on app/flows/prozesskostenhilfeFormular/finanzielleAngaben/doneFunctions.ts
> +    hasStaatlicheLeistungen({ context })) ||
see above

2024-09-04 11:06 UTC, Spencer6497 commented on app/flows/prozesskostenhilfeFormular/finanzielleAngaben/doneFunctions.ts
> +      hasStaatlicheLeistungen({ context })) ||
see above

2024-09-04 11:06 UTC, Spencer6497 commented on app/flows/prozesskostenhilfeFormular/finanzielleAngaben/einkuenfte/doneFunctions.ts
> +      hasStaatlicheLeistungen({ context })) ||
see other comments but I'm not sure we should be skipping all einkünfte if the user has, say, Arbeitslosengeld or Bürgergeld?

2024-09-05 08:31 UTC, rbrtrfl commented on app/flows/prozesskostenhilfeFormular/finanzielleAngaben/doneFunctions.ts
>    ["no", "widowed"].includes(context.partnerschaft ?? "") ||
you are right! thats one staatliche Leistung too much :)

2024-09-05 08:55 UTC, rbrtrfl commented on app/flows/prozesskostenhilfeFormular/abgabe/flow.json
> -          "#ausgaben"
after my code changes, `hasStaatlicheLeistungen` and `hasNoStaatlicheLeistungen` is now again exclusively used by BerH. So I've changed the guards around the `BACK` route in PKH `#abgabe` 🤍

2024-09-05 08:57 UTC, rbrtrfl commented
@Spencer6497 thanks for helping finish my WIP for this subtask 😉

2024-09-05 09:33 UTC, Spencer6497 approved these changes
excellent work 🎉 🚢

2024-09-05 09:33 UTC, Spencer6497 commented on app/flows/prozesskostenhilfeFormular/finanzielleAngaben/doneFunctions.ts
> +      context.staatlicheLeistungen === "grundsicherung"
could use the more succinct `hasGrundsicherungOrAsylbewerberleistungen({
        context,
      }))` syntax but your choice :)

2024-09-05 12:08 UTC, merged