use pdfFillReducer to fill BerH pdf
digitalservicebund/a2j-rechtsantragstelle pull request #1175
Opened 2024-09-09 11:50 UTC by rbrtrfl

- move fillOutFunction one level up
- use pdfFillReducer to fill BerH pdf

2024-09-09 14:27 UTC, Spencer6497 requested changes
Great work on this 🙌 though I'm fairly certain there's a logical error where noted ⬇️

2024-09-09 14:27 UTC, Spencer6497 commented on app/services/pdf/beratungshilfe/sections/F_besitz/F_besitz.ts
> +};
we should be destructuring and returning the result of `pdfFillReducer`, like so:
```
const { pdfValues, attachment } = pdfFillReducer(...)
return {
    pdfValues,
    attachment
}
```

does the way it currently is work?

2024-09-09 14:27 UTC, Spencer6497 commented on app/services/pdf/beratungshilfe/sections/G_ausgaben.ts
> +  const isPdfFieldExceedsMaxChars = userData.ausgaben?.some(
```suggestion
  const isPdfFieldExceedsMaxChars = ausgaben.some(
```

2024-09-13 20:33 UTC, rbrtrfl commented on app/services/pdf/beratungshilfe/sections/F_besitz/F_besitz.ts
> +};
you are absolutely right!

2024-09-13 20:50 UTC, rbrtrfl commented on app/services/pdf/beratungshilfe/sections/A_angelegenheit.ts
> +}) => {
As far as I understand, a type alias like `BerHPdfFillFunction` can only be used like this with anonymous function definitions. If we would go for a named function, explicit typing for parameters and return value would be necessary.

2024-09-16 05:34 UTC, Spencer6497 approved these changes

2024-09-16 12:48 UTC, chohner approved these changes
lgtm

2024-09-16 13:06 UTC, merged