feature/remove-checkobox-underage-for-main-plaintiff: update tests, flow, guards and  doneFunction
digitalservicebund/a2j-rechtsantragstelle pull request #1187
Opened 2024-09-11 15:39 UTC by judithmh

2024-09-12 11:24 UTC, judithmh commented on app/flows/fluggastrechteFormular/persoenlicheDaten/doneFunctions.ts
> +  //const hasPersonVertretung = hasPersonVertretungData({ context });
ah forgot to delete it sorry

2024-09-12 11:24 UTC, judithmh commented on app/flows/fluggastrechteFormular/persoenlicheDaten/doneFunctions.ts
> +  return hasPersonData; //&& hasPersonVertretung;
also forgot to delete it :D

2024-09-12 12:07 UTC, pgurusinga approved these changes

2024-09-16 11:15 UTC, aaschlote requested changes
The attribute `unter18JahreAlt` still exists in the contex.ts (app/flows/fluggastrechteFormular/persoenlicheDaten/context.ts). Can you please remove it?

2024-09-16 11:15 UTC, aaschlote commented on app/flows/fluggastrechteFormular/persoenlicheDaten/doneFunctions.ts
> -  const hasPersonVertretung = hasPersonVertretungData({ context });
can you get rid the `hasPersonVertretungData`? It's declared above but it hasn't used anywhere

2024-09-16 11:17 UTC, aaschlote commented on app/flows/fluggastrechteFormular/persoenlicheDaten/doneFunctions.ts
> +  return hasPersonData;
you can simplify this function like this if you want:

```
return objectKeysNonEmpty(context, [
    "vorname",
    "nachname",
    "strasseHausnummer",
    "plz",
    "ort",
  ]);
```

2024-09-16 16:02 UTC, aaschlote commented on app/flows/fluggastrechteFormular/persoenlicheDaten/context.ts
>    ...fluggastrechtePersoenlichVertretungDaten,
I believe we don't need more this data, can you please check it?

2024-09-17 07:24 UTC, judithmh commented on app/flows/fluggastrechteFormular/persoenlicheDaten/context.ts
>    ...fluggastrechtePersoenlichVertretungDaten,
I think we do need it because here it is an attribute for "weitere Personen" and not for the first person filing the claim

2024-09-17 15:05 UTC, judithmh commented on app/flows/fluggastrechteFormular/persoenlicheDaten/context.ts
>    ...fluggastrechtePersoenlichVertretungDaten,
Ah but the one you are referring to is already not there anymore I believe? It shows line 20 has been removed

2024-09-18 13:46 UTC, aaschlote approved these changes
LGTM

2024-09-18 14:22 UTC, merged