doc: Add ADR for domain-oriented architecture
digitalservicebund/a2j-rechtsantragstelle pull request #1270
Opened 2024-10-07 10:56 UTC by frederike-ramin

As discussed in the Dev Exchange.

2024-10-07 11:30 UTC, aaschlote commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
A few things mentioned here are related react components, for those things I would like to keep maybe in the `components` folder, the others things for non-react components I feel it's ok to move to the domain folder.

2024-10-07 11:49 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
You mean these two?

>   - `WEITERE_PERSONEN_START_INDEX` in the ArraySummaryDataItems
>   - `FluggastrechteResultPage` in components

The first one, I do think we need a domain-agnostic way of handling. We might not only want a different indexing for the one specific "personen" use case but for others as well.

The second one is debatable, yes. However, the easiest solution would just be to move the component into the according `route` and we'd be done. :)

2024-10-07 11:56 UTC, aaschlote commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
I was thinking also to maybe inside the `domain` a subfolder called `components`, only contain the react components for the domain.

For the `WEITERE_PERSONEN_START_INDEX` it seems a new version of the `stringReplacements` for `ArraySummary`, it could be new function inside the `arrayConfig`. But we can discuss it also.

My strong feeling is having the react components inside a specific folder and the most common (and I believe everybody also does the same) is the `components` one.

2024-10-07 12:04 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
Yes. I left the "todos" without specific solutions yet so that we had exactly those conversations afterwards. I'm also not 100% clear on how to solve the `WEITERE_PERSONEN_START_INDEX` issue. Your suggestion sounds interesting, let's explore that. 

> My strong feeling is having the react components inside a specific folder

Not arguing with you there at all. I think so too.

2024-10-08 07:41 UTC, aaschlote commented on doc/adr/0012-domain-oriented-architecture.md
> +# 11. Splitting domain configurations and application logic
should be 12, not?

2024-10-08 09:16 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
what is progress configuration? I don't think that exists anymore 🤔

2024-10-08 09:16 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Strapi "extra" flowIDs
What this? 🤔

2024-10-08 09:16 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - airport data + logic
Maybe rather `domain specific data, for example airports` ?

2024-10-08 09:34 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- There might be a domain-overarching folder called `shared` for domains very similar to each other, like `beratungshilfe`and `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`
Yes, probably. I'd say that's up for the "domain owners" then though?

2024-10-08 09:36 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
I knew the naming was confusing. Do you have a better name for this?
https://github.com/digitalservicebund/a2j-rechtsantragstelle/blob/c3a7230f73a6c85d96ff12f1275e40ec7e8d61d1/app/services/flow/server/progress.ts#L56

(Only found this because I searched for "beratungshilfe" ;)

2024-10-08 09:39 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Strapi "extra" flowIDs
I was also surprised to find this^^: https://github.com/digitalservicebund/a2j-rechtsantragstelle/blob/main/app/services/cms/models/StrapiFlowId.ts

2024-10-08 09:48 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +However, some parts of the domain configuration still reside in other modules, e.g. the PDF filling logic.
I added a sentence but omitted the "uncertainty" part, sounded a little too self-rightous to me^^

2024-10-08 10:25 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
aha! But this isn't configuration and shouldn't be defined inside a flow imo

But interesting point, we don't really have a mechanism to do something for a subset of flows, ie all vorabchecks.

However, this might be addressed by having a root configuration:

```typescript
export const vorabcheckIds = ["a", "b"] as const; // Used inside the progress service
export const formFlowIds = ["c", "d"] as const;
export const flowIds = [...vorabcheckIds, ...formFlowIds] as const;
export type FlowIds = typeof flowIds;
```

(I don't think this needs to be part of this ADR)

2024-10-08 10:28 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Strapi "extra" flowIDs
WHICH IDI... oh. 😇

This is a weird one but I would rather say this is not a "normal" configuration property.

Similar to above, this may also disappear by having some root configuration

2024-10-08 10:30 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +- There might be a domain-overarching folder called `shared` for domains very similar to each other, like `beratungshilfe`and `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`
Absolutely. But I think describing this pattern here explicitly might be helpful

2024-10-08 10:32 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +- flowId: The identifier to differentiate between different flows, e.g. `/beratungshilfe/vorabcheck`
I think actually there is a different concept that we never spoke about: Flow type (?), ie `vorabcheck` and `flow` (differ on progress bar, side navigation, funnel logic) 🤔

2024-10-08 13:06 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- There might be a domain-overarching folder called `shared` for domains very similar to each other, like `beratungshilfe`and `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`
Okay, could you prepare a sentence? Not sure how I would phrase that.

2024-10-08 13:52 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Strapi "extra" flowIDs
I still kind of like the idea to handle "/beratungshilfe/zustaendiges-gericht" as another flow you mentioned in a call.

2024-10-08 13:52 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- flowId: The identifier to differentiate between different flows, e.g. `/beratungshilfe/vorabcheck`
You're right. Can we make this another ADR though?

2024-10-08 14:23 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
I think my only challenge is that there is nothing to configure, because its fundamentally based on the "type" of the flow (vorabcheck vs flow). So for now I wouldn't include it in the canonical list of things that should be configurable

2024-10-08 14:23 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Strapi "extra" flowIDs
see above - then lets remove it from the list of configurable things and rather add it as a tech debt ticket to refactor?

2024-10-09 13:04 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
Mh..how do you define then which flow gets a progress and which doesn't? just because of the name "vorabcheck"? I'd think that's quite dangerous?

2024-10-09 13:27 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Strapi "extra" flowIDs
Aahhh..now I see the point of your comment(s)! To you, it's about sorting out only the configuration. So "What isn't 'configuration' is 'core'. To me, I'm always thinking the other way around: "What isn't 'core', has to be configuration. But I see your point and we can just have it as a refactoring ticket and I'll remove it here.
It also seems to align neatly with  [this ask](https://digitalservicebund.slack.com/archives/C031NV6FMQA/p1728464861234759) by Marion, I'd say.

2024-10-09 14:15 UTC, ekl176 approved these changes

2024-10-09 16:31 UTC, manuelpuchta approved these changes

2024-10-09 16:31 UTC, manuelpuchta commented on doc/adr/0012-domain-oriented-architecture.md
> +Currently, we are mostly separating the domains' configurations from the application logic withing the folder "flows".
Nit, little typo:
```suggestion
Currently, we are mostly separating the domains' configurations from the application logic within the folder "flows".
```

2024-10-09 16:31 UTC, manuelpuchta commented on doc/adr/0012-domain-oriented-architecture.md
> +We follow the following naming:
Nit:
```suggestion
We strive for the following naming:
```

2024-10-09 16:31 UTC, manuelpuchta commented on doc/adr/0012-domain-oriented-architecture.md
> +- There might be a domain-overarching folder called `shared` for domains very similar to each other, like `beratungshilfe`and `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`
Nit:
```suggestion
- There might be a domain-overarching folder called `shared` for domains very similar to each other, like `beratungshilfe` and `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`.
```

And in regards to your discussion, without detailed knowledge about that part, maybe something like that is already understandable enough:
> Logic that is useful for multiple domains or flows, like `beratungshilfe`, `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`, shall be moved into a dedicated `shared` folder

2024-10-10 08:32 UTC, zechmeister approved these changes

2024-10-10 08:32 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Possibly: Domains do not "interfere" with each other quite that much as they are kept separate.
@aaschlote you asked for more specific advantages on the day-to-day basis. I'm struggeling a bit with this, as these pretty much already sum it up for me. Do you have more thoughts on this where I could improve the benefits?

2024-10-10 09:38 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
Currently the only thing that is specifically different between vorabcheck and flow pages is `cmsSlug` (I think). The progress calculation depending on "type" is mostly a performance optimization..

How about each configuration exposing a `type FlowType = "vorabcheck" | "full-flow"`, which services can consume?
- the content lookup service can configure the fitting api endpoint
- the progress can filter by `type === "vorabcheck"`
- ....

2024-10-10 11:07 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
Yes, love it. Great solution. Just to be clear: I'll leave it as a Todo here then. The concrete solution comes when solving it. 👍

2024-10-10 11:38 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
I still believe that it does not belong in this list of explicit things that are in the configuration domain of a flow and would rather remove it here

2024-10-10 12:09 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +  - Vorabcheck progress configuration
Misunderstanding resolved in: https://github.com/digitalservicebund/a2j-rechtsantragstelle/pull/1270/commits/70c776707aa5435520c8f76938b6135918a72fea

2024-10-10 12:09 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- flowId: The identifier to differentiate between different flows, e.g. `/beratungshilfe/vorabcheck`
Added in: https://github.com/digitalservicebund/a2j-rechtsantragstelle/pull/1270/commits/70c776707aa5435520c8f76938b6135918a72fea

2024-10-10 12:30 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +- Configurations that are useful for multiple domains or flows, like `beratungshilfe`, `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`, shall be moved into a dedicated `shar
Could we replace these two hard-to-read bullet points with a diagram?


- In terms of folder structure, flow configurations are scoped by their domain. Shared code should be placed in a `shared` folder that may exist on any level:
	```
	.
	└── domains
	    ├── fluggastrecht
	    │    ├── vorabcheck
	    │    │    ├── index.ts      # Exports full flow configuration
	    │    │    ├── schemas
	    │    │    ├── stringReplacements
	    │    │    └── guards
	    │    ├── formular
	    │    │    ├── index.ts
	    │    │    └── pdf           # flow specific pdf logic
	    │    └── shared             # Shared code inside domain
	    ├── beratungshilfe
	    │    ├── vorabcheck
	    │    └── antrag
	    └── shared                  # Shared code across cross-domain, ie:
	         ├── persoenlicheDaten	# Common sub-flow configuration
	         └── schemas            # Useful schemas
	```

2024-10-10 13:00 UTC, rbrtrfl reviewed
nice initiative. I've left some minor comments/questions.

2024-10-10 13:54 UTC, chohner commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
Not all but only domain/flow specific ones (which we probably will only have very very few)

2024-10-10 14:37 UTC, pgurusinga commented on doc/adr/0012-domain-oriented-architecture.md
> +- Configurations that are useful for multiple domains or flows, like `beratungshilfe`, `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`, shall be moved into a dedicated `shar
Yes, I would love to see the difference; the one before the change and the one after it.

2024-10-10 16:12 UTC, aaschlote commented on doc/adr/0012-domain-oriented-architecture.md
> +- Configurations that are useful for multiple domains or flows, like `beratungshilfe`, `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`, shall be moved into a dedicated `shar
it should be inside, check this [link](https://github.com/digitalservicebund/a2j-rechtsantragstelle/pull/1270#discussion_r1795332044)

2024-10-10 16:17 UTC, aaschlote commented on doc/adr/0012-domain-oriented-architecture.md
> +- Possibly: Domains do not "interfere" with each other quite that much as they are kept separate.
I'm having a bit of trouble fully grasping the value of the proposal compared to our current implementation. It might be because I'm so used to the existing setup, or perhaps I'm not seeing the complete picture of the new approach.

That's why I suggested including some references or examples from other sources, to help me view the proposal from a different perspective 😃.

My opinion could definitely change once we have everything in place and I see it in action.

2024-10-10 19:12 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
Wait, I understood Alex' suggestion was to *not* have components outside the `/app/components` folder? Because atm the only one we have, is the FluggastrechteResultPage and that can just reside in the routes ✅ ?

2024-10-10 19:20 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
If that is the case (please confirm, @aaschlote) then we can for the sake of this PR remove the mention of `FluggastrechteResultPage` here and instead make it a refactoring task. :)

2024-10-10 19:23 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Configurations that are useful for multiple domains or flows, like `beratungshilfe`, `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`, shall be moved into a dedicated `shar
Committed it as you suggested. Thank you, that makes it very clear. 👍

2024-10-10 19:24 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Configurations that are useful for multiple domains or flows, like `beratungshilfe`, `prozesskostenhilfe` or domain-irrelevant things like `persoenlicheDaten`, shall be moved into a dedicated `shar
@pgurusinga if you want the current state you can probably check the repo, right? No need to specify it here or would you disagree?

2024-10-11 09:31 UTC, aaschlote commented on doc/adr/0012-domain-oriented-architecture.md
> +- Things that are now specific to one service should reside in the `domains` folder. That includes:
I meant what @rbrtrfl and @chohner said, we can have react components inside of the domain with a subfolder `components`, for specific react components of the domain or flow, like the `FluggastrechteResultPage`.

I won't like to see the react components inside of non `components` folder.

2024-10-14 12:57 UTC, frederike-ramin commented on doc/adr/0012-domain-oriented-architecture.md
> +- Possibly: Domains do not "interfere" with each other quite that much as they are kept separate.
Okay, I see. In my head it goes into the way of Configuration-drive Architecture: https://www.bro-code.in/blog/configuration-driven-architecture
Only that the configuration is done by code and not JSON/YAML (therefor needing a deployment for changes).
Does that link help you? Then I can include it in the ADR.

2024-10-14 13:50 UTC, aaschlote commented on doc/adr/0012-domain-oriented-architecture.md
> +- Possibly: Domains do not "interfere" with each other quite that much as they are kept separate.
yeap, this helps me :)

2024-10-14 14:29 UTC, rbrtrfl approved these changes

2024-10-14 14:33 UTC, pgurusinga approved these changes

2024-10-14 15:08 UTC, m0dh4x requested changes
i think this applies to both worlds, so no drawback here in particular. I even think it's a bit clearer when you're working on something that affects both of the domains or all upcoming ones

"Expected drawbacks:

There might be more communication efforts necessary when changing application logic as it affects other/all domains."

2024-10-14 15:52 UTC, frederike-ramin commented
@m0dh4x yes, you're right. Are you suggesting to remove the drawbacks section in total?

2024-10-14 16:11 UTC, aaschlote approved these changes

2024-10-14 16:37 UTC, m0dh4x approved these changes

2024-10-17 13:18 UTC, merged