test(flows): add coverage
digitalservicebund/a2j-rechtsantragstelle pull request #1508
Opened 2024-12-02 14:32 UTC by chohner

- adds coverage for step Ids visited during flow tests
- sets upper bound for untested steps

2024-12-02 16:15 UTC, rbrtrfl commented on app/domains/__test__/flows.test.ts
> +    expect(totalMissingStepCount).toBeLessThanOrEqual(126);
So this number is our current lucky number of untested steps? Do we want to remove this assertion after having filled the gaps or how do we plan to use it?

Suggestion: I think it would be useful to get the missing steps printed out within the failing assertion logs, not as a `console.warn` (under the assumption that we're moving towards zero missing steps).

2024-12-02 16:15 UTC, rbrtrfl commented on app/domains/__test__/flows.test.ts
> +    const missingStepsEntries = Object.entries(allVisitedSteps)
I find this variable name misleading, because it basically holds all visited steps, not only the missing steps, or?

2024-12-03 17:29 UTC, chohner commented on app/domains/__test__/flows.test.ts
> +    const missingStepsEntries = Object.entries(allVisitedSteps)
no, its only missing steps (note the `.map()` call)

2024-12-03 17:29 UTC, chohner commented on app/domains/__test__/flows.test.ts
> +    expect(totalMissingStepCount).toBeLessThanOrEqual(126);
Right, this blocks anyone from adding new untested flow steps. Once we actively put effort into reducing this number we can keep decreasing it

2024-12-05 10:36 UTC, Spencer6497 approved these changes
excellent! This'll help a lot 👍

2024-12-05 10:36 UTC, Spencer6497 commented on app/domains/__test__/flows.test.ts
> +describe.sequential("state machine form flows", () => {
what's the purpose behind the `.sequential`/`.concurrent` calls?

2024-12-05 10:48 UTC, aaschlote requested changes
I appreciate the idea, but I’m not entirely on board with how this check has been implemented.

In my opinion, having a unit test fail because a certain number of tests are missing doesn’t make much sense. Why? Tests should be an integral part of the development process, and their absence shouldn't act as a blocker. If tests are missing, the question to ask is: why weren’t they created in the first place?

I believe this functionality would be more effective as a script that runs periodically, analyzing how many steps are missing tests. This way, we can address gaps over time without hindering the development process.

Moreover, I would strongly challenge any developer who creates new features or refactors existing ones without adding tests. Failing to write or include necessary tests reflects a significant issue in the quality of the product. Ensuring that every change is accompanied by appropriate tests is a fundamental responsibility, and it’s crucial for maintaining high standards in our work.

2024-12-10 16:13 UTC, aaschlote approved these changes
As we discussed, let's keep like this for now and iterate later  😃

2024-12-12 08:58 UTC, merged