refactor: rename `suggestion-input` to `auto-suggest-input`.
digitalservicebund/a2j-rechtsantragstelle pull request #888
Opened 2024-06-06 12:54 UTC by eliflores

related to https://github.com/digitalservicebund/a2j-rechtsantragstelle-strapi/pull/275

2024-06-06 13:06 UTC, aaschlote commented
Missing the story file `SuggestionInput.stories.tsx` to rename  and the function fillMultipleSuggestionInputPage

2024-06-06 13:08 UTC, aaschlote requested changes

2024-06-06 13:08 UTC, aaschlote commented on stories/SuggestionInput.stories.tsx
>    title: "Component/SuggestionInput",
here as well

2024-06-06 13:08 UTC, aaschlote commented on stories/SuggestionInput.stories.tsx
>    name: "suggestionInput",
we need to rename here too

2024-06-06 14:24 UTC, eliflores commented on stories/SuggestionInput.stories.tsx
>    title: "Component/SuggestionInput",
Good catch ✨ 
Done in [fbf9e82](https://github.com/digitalservicebund/a2j-rechtsantragstelle/pull/888/commits/fbf9e827bfcbe014ccbba05aac8a84c2579006ee)

2024-06-06 14:25 UTC, eliflores commented on stories/SuggestionInput.stories.tsx
>    name: "suggestionInput",
👍 Done in [fbf9e82](https://github.com/digitalservicebund/a2j-rechtsantragstelle/pull/888/commits/fbf9e827bfcbe014ccbba05aac8a84c2579006ee)

2024-06-07 11:30 UTC, aaschlote approved these changes

2024-06-07 11:31 UTC, merged