Create user feedback component from Strapi
digitalservicebund/a2j-rechtsantragstelle pull request #950
Opened 2024-06-26 12:32 UTC by aaschlote

2024-07-01 13:42 UTC, chohner commented on app/components/UserFeedback/UserFeedbackContext.tsx
> +  flowId?: string;
I think `flowId` is the wrong variable name here, as it describes what exactly is being rated. Originally it was named `context` but maybe `pathname` is actually the correct word?

2024-07-01 13:46 UTC, chohner commented on app/components/UserFeedback/UserFeedbackContext.tsx
> +  flowId?: string;
Also, could we type this as an optional object, instead of an object with two optional properties? so if the object is there, both properties can be accessed?

2024-07-01 13:50 UTC, chohner requested changes

2024-07-01 13:50 UTC, chohner commented on app/components/resultPage/DefaultResultPage.tsx
> +  const userFeedbackContextValue = useMemo(
Could this be moved into `StrapiUserFeedback`?

2024-07-01 13:50 UTC, chohner commented on app/components/resultPage/FluggastrechteResultPage.tsx
> +  const userFeedbackContextValue = useMemo(
this could also be left untouched if the hook is moved into `StrapiUserFeedback`

2024-07-01 13:50 UTC, chohner commented on app/routes/shared/feedback.server.ts
> +};
I think the existing `/actions/send-feedback` pattern is much cleaner, as we don't need to repeatedly export the same action from all routes. also, combining actions might be a hassle in the future

2024-07-01 13:57 UTC, aaschlote commented on app/components/resultPage/DefaultResultPage.tsx
> +  const userFeedbackContextValue = useMemo(
I could, but I would need to pass the `bannerState` and `flowId` as props of the `PageContent` and pass it again to  `StrapiUserFeedback`. So using the context wouldn't make so much more difference. To have a lower level of abstraction and avoiding unneeded props I created this context, so I can access only I need it

2024-07-01 14:03 UTC, aaschlote commented on app/routes/shared/feedback.server.ts
> +};
I don't fully understand what you mean here. 

I created this file to be exported in a few places where we don't handle the `feedback` in the action. In this case on the content pages.

I didn't find the existing one you mentioned `/actions/send-feedback`, only the `action/send-rating`. This what do you mean?

2024-07-01 14:09 UTC, aaschlote commented on app/components/UserFeedback/UserFeedbackContext.tsx
> +  flowId?: string;
I was strangling about the naming of this variable, because on the feedback layer is called context, but on the flow layer is `flowId`. Not sure what it's the best one, but for me when I get the `flowId` and pass to the props `context` is sounds a better weird. But I can change it if you prefer this name.

About the both object to be optional, the problem I was facing it's that the BannerState is an enum and it's defined the default value of the context when it's created and I have some errors to define it, for this reason I was forced to make it as optional, but it should be always with a value.

2024-07-01 15:40 UTC, chohner commented on app/routes/shared/feedback.server.ts
> +};
Sorry for being unclear - yes I meant adding a new `actions/send-feedback` endpoint that handles the feedback action. The url would then be hard-coded in the `action` of that form

2024-07-01 15:42 UTC, chohner commented on app/components/resultPage/DefaultResultPage.tsx
> +  const userFeedbackContextValue = useMemo(
but I thought thats what the context is doing? or alternatively move the context one level up - I thought having 3+ times the same context looks a bit fishy

2024-07-01 15:51 UTC, aaschlote commented on app/components/resultPage/DefaultResultPage.tsx
> +  const userFeedbackContextValue = useMemo(
the another level up it's the root and inside of the root I don't have the information about the `flowId` 😞

2024-07-02 07:33 UTC, chohner commented on app/components/UserFeedback/UserFeedbackContext.tsx
> +  flowId?: string;
but what is called `flow id` here is just the name of what is being rated, right? if this component can live on any page this should be exclusively obtainable from the pathname

2024-07-02 07:33 UTC, chohner commented on app/components/resultPage/DefaultResultPage.tsx
> +  const userFeedbackContextValue = useMemo(
see above: I don't think we need a flow id - we just need to know what page is being rated

2024-07-02 07:52 UTC, aaschlote commented on app/components/UserFeedback/UserFeedbackContext.tsx
> +  flowId?: string;
As I mentioned in my comment above, on the flow layer context is `flowID` but on this component is called `context`. I didn't name them like this, you can see in the image and the following [link](https://github.com/digitalservicebund/a2j-rechtsantragstelle/blob/main/app/components/resultPage/ResultPage.tsx#L181)

<img width="997" alt="image" src="https://github.com/digitalservicebund/a2j-rechtsantragstelle/assets/11893663/d3645686-5b96-4de0-aee4-48ff709c2d4d">

The `flowId` is optional in this component, so for this reason can be used in any page. I didn't make this change, it was already implemented like this.

If you feel the name in this react context should be `context` instead of `flowId` I can change, but it sounds a bit weird for me, but no harding feeling to change it.

2024-07-02 07:53 UTC, aaschlote commented on app/routes/shared/feedback.server.ts
> +};
I see what you mean, I will check it

2024-07-02 11:53 UTC, aaschlote commented on app/components/UserFeedback/UserFeedbackContext.tsx
> +  flowId?: string;
so, you are saying this props `context` in the [RatingBox.tsx](https://github.com/digitalservicebund/a2j-rechtsantragstelle/blob/main/app/components/UserFeedback/RatingBox.tsx#L42) is unless and I can get rid of it? Because we are using already the `pathname` in the props `url`.

![image](https://github.com/digitalservicebund/a2j-rechtsantragstelle/assets/11893663/3938871c-9d3a-4940-a841-0721c3516801)

2024-07-02 12:26 UTC, pgurusinga commented on app/routes/shared/feedback.server.ts
> +};
I would honestly use different PR or commit for that since it's a different scope than just strapify the component

2024-07-03 07:12 UTC, aaschlote commented on app/routes/shared/feedback.server.ts
> +};
I found sometime yesterday and I implemented it :)

2024-07-03 08:31 UTC, pgurusinga commented on app/components/UserFeedback/FeedbackFormBox.tsx
> -
why is this deleted? how then are we showing the user after submitting data?

2024-07-03 08:31 UTC, pgurusinga commented on app/components/UserFeedback/FeedbackFormBox.tsx
> -        action={nextDestination}
also related to one above

2024-07-03 08:35 UTC, pgurusinga commented on app/root.tsx
> +      getFeedbackBannerState(mainSession, pathname) ?? BannerState.ShowRating,
if this defaults to `BannerState.ShowRating` could you explain why `useUserFeedback()` in the component has default arguments with the same value? 
`const { bannerState = BannerState.ShowRating } = useUserFeedback();`

2024-07-03 08:38 UTC, aaschlote commented on app/components/UserFeedback/FeedbackFormBox.tsx
> -
I created a new route (`action.send-feedback`), the whole logic is there :)

2024-07-03 08:41 UTC, aaschlote commented on app/root.tsx
> +      getFeedbackBannerState(mainSession, pathname) ?? BannerState.ShowRating,
I had a problem with the context `UserFeedbackContext`. I couldn't make the context have a default value due the type is an enum and it was throwing some errors on the page. So I was forced to make it as optional. When it's used the hook `useUserFeedback()` the value of the bannerState can be `undefined`, so again I have to pass a default value.

If you want we can pair programming on it and try to find a solution.

2024-07-04 09:55 UTC, pgurusinga approved these changes

2024-07-04 10:54 UTC, chohner approved these changes
some nitpicks

2024-07-04 10:54 UTC, chohner commented on app/routes/$.tsx
I think this could be fully reverted to decrease the diff?

2024-07-04 10:54 UTC, chohner commented on app/routes/action.send-feedback.ts
> +    : `${url}#${USER_FEEDBACK_ID}`;
what happens if we always redirect to `${url}#${USER_FEEDBACK_ID}`?

2024-07-04 10:54 UTC, chohner commented on app/routes/action.send-feedback.ts
> +    (session.get(bannerStateName) as Record<string, BannerState>) ?? {};
there is probably a lot of data shared with `send-rating`... maybe for future cleanup

2024-07-04 10:54 UTC, chohner commented on app/routes/action.send-feedback.ts
> +  const formData = await request.clone().formData();
I think we dont need to clone here (anymore), since the data will only come from the dedicated form

2024-07-04 10:54 UTC, chohner commented on app/routes/action.send-rating.ts
> +const getContextByUrl = (url: string): string => {
maybe rather `parseFlowIdFromUrl`?

2024-07-04 11:02 UTC, pgurusinga commented on app/routes/action.send-feedback.ts
> +    : `${url}#${USER_FEEDBACK_ID}`;
toThe `preventScrollReset` for the Y-Axis in the form will not work as intended; it is always positioned at the top. The design requires it to remain in place for JS users upon form submission.

2024-07-04 11:03 UTC, pgurusinga commented on app/routes/action.send-feedback.ts
> +    (session.get(bannerStateName) as Record<string, BannerState>) ?? {};
@aaschlote might be a TODO for Fixathon?

2024-07-04 12:15 UTC, aaschlote commented on app/routes/action.send-feedback.ts
> +    (session.get(bannerStateName) as Record<string, BannerState>) ?? {};
I'll add it

2024-07-04 13:31 UTC, merged